// react-todo-app-copy/src/components/TodoList.js
import React, { useState, createContext } from "react";
import TodoListItem from './TodoListItem';
import TodoAddItemModal from './TodoAddItemModal';
import TodoListHero from "./TodoListHero";

import {
   DndContext,
   closestCenter,
 } from '@dnd-kit/core';
 import {
   arrayMove,
   SortableContext,
   // sortableKeyboardCoordinates,
   // useSortable,
   verticalListSortingStrategy,
 } from '@dnd-kit/sortable';
 //import { CSS } from '@dnd-kit/utilities';
 import { restrictToVerticalAxis } from '@dnd-kit/modifiers';


// Create context for the tasks to be used in child components
const TodoListContext = createContext();


/**
 * A React component that manages a todo list.
 */
function TodoList() {
   /*
   useState is a React hook that allows us to manage state in a functional component.

   The hook takes an initial state as an argument. For example:
      const [count, setCount] = useState(0);

   In this case the hook's initial state is set to an array of task objects, each with
   an `id`, `text`, and `completed` property.      

   It returns an array with two elements: the current state and a function to update it.
      The current state (tasks) is stored in the first element of the array.
      The function to update the state (setTasks) is stored in the second element of the array.
   */
   const [tasks, setTasks] = useState([]);

   // set default tasks
   const [defaultTasks] = useState([
      {
         id: 1,
         text: "Edit item  - watch out for long text lines that wrap",
         duedate: "2099-01-01 12:00",
         completed: true,
         position: 1
      },
      {
         id: 2,
         text: "Reorder with drag and drop",
         duedate: "2024-12-31 09:00",
         completed: false,
         position: 2
      },
      {
         id: 3,
         text: "Redux state management(?)",
         duedate: "",
         completed: false,
         position: 3
      },
      {
         id: 4,
         text: "Store todo list in local storage",
         completed: true,
         position: 4
      }
   ]);


   // handle dnd kit drag end event when reordering and update the task positions
   const handleDragEnd = (event) => {
      const { active, over } = event;
   
      // Check if 'over' is not null before proceeding
      if (over && active.id !== over.id) {
         setTasks((tasks) => {
            const oldIndex = tasks.findIndex(task => task.id === active.id);
            const newIndex = tasks.findIndex(task => task.id === over.id);

            // Move the task within the array
            const reorderedTasks = arrayMove(tasks, oldIndex, newIndex);

            // Update the position based on the new index
            const updatedTasks = reorderedTasks.map((task, index) => ({
               ...task,
               position: index + 1,
            }));

            // Update localStorage with the new positions
            localStorage.setItem('tasks', JSON.stringify(updatedTasks));

            return updatedTasks;
         });
      }
   };

/* eslint-disable no-unused-vars */
   const handleDragEndORIGINAL = (event) => {
      const { active, over } = event;
   
      // Check if 'over' is not null before proceeding
      if (over && active.id !== over.id) {
         setTasks((tasks) => {
            const oldIndex = tasks.findIndex(task => task.id === active.id);
            const newIndex = tasks.findIndex(task => task.id === over.id);

            console.table('tasks after:', tasks);
   
            return arrayMove(tasks, oldIndex, newIndex);
         });
      }
   };
/* eslint-enable no-unused-vars */

   // State variable 'filter' is used to store the current value of the task filter menu (default is 'All')
   const [filter, setFilter] = useState('All');

   /*
   useState accepts an initial state and returns two values:
   1. The current state (showModal)
   2. A function that updates the state (setShowModal).

   State variable (showModal) for "add todo" modal window is set to false to hide the modal by default
   when the <TodoAddItemModal /> component is initially rendered from TodoAddItemModal.js.

   The second parameter (setShowModal) is the function used to update the value of 'showModal' which
   will show/hide the modal component.
   */
   const [showModal, setShowModal] = useState(false);

   // State var to adjust modal window heading (e.g. "Add Todo" or "Edit Todo") - default "Add"
   const [addEditMode, setAddEditMode] = useState('Add');

   // State var to store current task id being edited when a user clicks the edit button
   const [currentTaskId, setCurrentTaskId] = useState(null);

   const completedTasks = tasks.filter(task => task.completed).length;
   const totalTasks = tasks.length;


   /*
   Retrieve tasks from localStorage when the component mounts passing the 
   defaultTasks array as a dependency to control when the effect runs.
   
   The effect runs when the defaultTasks array changes. Since the defaultTasks
   array shouldn't change, it's passed to avoid running the effect on every render
   when no dependency array is passed. An empty array could be used to run the effect
   once after the initial render though ESLint doesn't like that, so it's to satisfy 
   ESLint when we run `npm run build`.
   */
   React.useEffect(() => {
      const storedTasks = localStorage.getItem('tasks');
      if (storedTasks) {
         setTasks(JSON.parse(storedTasks));
      }
      else {
         setTasks(defaultTasks);
      }
   }, [defaultTasks]);


   // Helper function (addTask) - creates a new task object with a unique `id`, `text`, and `completed` property.
   // The new task object is added to the `tasks` array using the `setTasks` function.
   // Resets the `text` state to an empty string.  
   function addTask({ text, dateTime }) {
      // if text is not empty, create a new task object
      if (text !== '') {
         const newTask = {
            id: Date.now(),
            text,
            duedate: dateTime,
            completed: false,
            // get highest position + 1
            position: tasks.reduce((maxPos, task) => (task.position > maxPos ? task.position : maxPos), 0) + 1
         };

         // update `tasks` state with new task
         setTasks([...tasks, newTask]);
         
         // store updated tasks in local storage converting the tasks array of objects to a JSON string
         const updatedTasksList = JSON.stringify([...tasks, newTask]);
         localStorage.setItem('tasks', updatedTasksList);
      }
      else {
         // alert('Please enter some text');
      }
   }

   /*
   Helper function (deleteTask) - deletes a task by `id` from the `tasks` array using the `setTasks` function.
   The `tasks` array is filtered to remove the task with the matching `id` being marked for deletion.
   When deleting a task, we return a list that EXCLUDES the task we want to delete.
   The `tasks` array uses an arrow function.
   */
   function deleteTask(id) {
      setTasks(tasks.filter(task => task.id !== id));

      // ? the above is equivalent to the following which uses the older function() callback syntax:
      /*
      setTasks(tasks.filter(function(task) {
          return task.id !== id;
      }));
      */

      // update localStorage after deleting item (convert tasks array to JSON string)
      const updatedTasksList = JSON.stringify(tasks.filter(task => task.id !== id));
      localStorage.setItem('tasks', updatedTasksList);
   }


/* eslint-disable no-unused-vars */

   // Helper function (toggleCompleted) - toggles the `completed` property of a task by `id` using the `setTasks` function.
   function toggleCompletedOld(id)
   {
      // This works without using LocalStorage, but when we toggle an item, 
      // the tasks array isn't updated using setTasks() due to looping through
      // the array
      setTasks(
         tasks.map(task => {
            if (task.id === id) {
               return { ...task, completed: !task.completed };
            } else {
               return task;
            }
         })
      );

      // When viewing the tasks array in the console, we can see the toggled task value
      // is not updated in the array with the correct value. If we click the toggle again
      // the completed property does change, but not the correct value again.
      console.log('tasks array in toggleCompletedOld', tasks);

      // trying to update localStorage after marking item completed which will not work
      const updatedTasksList = JSON.stringify(tasks);
      localStorage.setItem('tasks', updatedTasksList);
   }


   // Helper function (toggleCompleted) - toggles the `completed` property of a task by `id` using the `setTasks` function.
   function toggleCompleted(id)
   {
      // tasks.map() returns the tasks array with a task with an updated completed property
      // so we will save the mapped array to a new array with the correct/current`completed` property 
      const updatedTasksArray = tasks.map(task => {
         if (task.id === id) {
            return { ...task, completed: !task.completed };
         } else {
            return task;
         }
      });
      
      // console.log('tasks array value (BAD completed):', tasks );
      // console.log('updated tasks array after array map (GOOD completed?):', updatedTasksArray );

      setTasks(updatedTasksArray);

      // update localStorage after marking item completed
      const completedTasksList = JSON.stringify(updatedTasksArray);
      localStorage.setItem('tasks', completedTasksList);
   }
   
   function arrowAndAnonFunctionExamples() {
      /*
      Some arrow and anonymous function examples
      */

      /*
      First a simple callback function (hello) with a parameter (val)
         - Function name: 'hello'
         - Parameter: (val)
      */
      const hello = (val) => "Hello " + val;
      console.log( hello('[WORLD]') );

      // Arrow function with no parameters
      //    Function name: 'hello2'
      //    Parameters: none
      const hello2 = () => {
         return "Hello World from hello2!";
      }

      console.log(hello2());

      // arrow function with 2 parameters
      const multiply = (a, b) => {
         return a * b;
      }

      console.log('multiply(5, 10): ', multiply(5, 10));


      // arrow function with no parameters, we define a variable named 'greet'
      var greet = () =>  
      { 
         console.log("An anonymous arrow function named 'greet' with no parameters"); 
      }

      // call the function using the variable name 'greet'
      greet(); 

      //  arrow function with a parameter
      var greet2 = (name) =>  
      { 
         console.log("An anonymous arrow function named 'greet' with a parameter named 'name'. Hi, " + name); 
      }

      greet2('Sally'); 

      // simple anonymous function which is invoked (called) using the variable name
      const x = function (a, b) {return a * b};
      console.log( x(2, 10) );

      /*
      A self-executing anonymous function (without the name itself) and will see how we may declare it as well as how we may call it in order to print the resultant value (ref: https://www.geeksforgeeks.org/javascript-anonymous-functions/).
      */
      (() => { 
         console.log("a self-executing anonymous function"); 
      })();

      /*
      Now with the above example in mind, now...

      * We're going to use an anonymous function in setTasks() like toggleCompletedAnonFunc() for
      * some of the more tricky cases like ones that use the map() function.

      We don't need all the extra parentheses like above. What we do need is:

      () => {
         // your code here

         return yourReturnValue;
      }

      For our purposes, we will use the anonymous function like above in setTasks() in the
      function toggleCompletedAnonFunc().

      setTasks(
         () => {
            // your code here
            return yourReturnValue;
         }
      );
      */
   }

/* eslint-enable no-unused-vars */
   function toggleCompletedAnonFunc(id) {
      /*
      Arrow/anonymous functions can be a bit confusing for people who aren't familiar with ES6.
      */

      // update `tasks` state using the `setTasks` function
      setTasks(
         // anonymous function in order to `return` the `updatedTasksArray` within the setTasks() function
         () => {
            // store the most recent tasks array after calling the map() function otherwise
            // we get a stale value for the completed property being toggled
            const updatedTasksArray = tasks.map(task => {
               if (task.id === id) {
                  return { ...task, completed: !task.completed };
               } else {
                  return task;
               }
            });

            // update localStorage after marking item completed
            const completedTasksList = JSON.stringify(updatedTasksArray);
            localStorage.setItem('tasks', completedTasksList);

            return updatedTasksArray;
      });
   }

/* eslint-disable no-unused-vars */

   function toggleCompletedAnonFuncOld(id) {
      /*
      Update the `tasks` array using the `setTasks` function.
      
      1. State Snapshot (prevTasks): prevTasks contains the current tasks array when setTasks is called.

      2. Updating Tasks: Using map, you create updatedTasks, modifying the 
         task with the specified id to toggle its completed status.
      
      3. Local Storage Update: Convert updatedTasks to a JSON string (updatedTasksList) and store it in localStorage.

      4. Returning Updated State: Finally, updatedTasks is returned from the function, setting it as the new state for tasks.
      */
      // ? arrow function version using an anonymous function
      setTasks(
         // `prevTasks` is the parameter of an anonymous function (arrow function) passed to `setTasks`
         (prevTasks) => {
            // Assign updated tasks (updatedTasks) from the current state of tasks (prevTasks)
            // that uses the `map` function to iterate through each task in the `tasks` array
            // and mark the current task as completed if the id matches the id toggled.
            const updatedTasks = prevTasks.map(task => {
            if (task.id === id) {
               return { ...task, completed: !task.completed };
            } else {
               return task;
            }
         });

         //console.log('updatedTasks: ', updatedTasks);

         // update localStorage after marking item completed
         const completedTasksList = JSON.stringify(updatedTasks);
         localStorage.setItem('tasks', completedTasksList);

         /*
         // debugging output
         const storedTasks = localStorage.getItem('tasks');
         if (storedTasks) {
            console.log(JSON.parse(storedTasks));
         }
         */

         // Return the updated tasks array to set it as the new state
         return updatedTasks;
      });
   }
/* eslint-enable no-unused-vars */


   // Helper function (updateTask) - updates the `text` property of a task by `id` using the `setTasks` function.
   function updateTask(id, newText, formattedDateTime) {
      // tasks.map() returns the tasks array with a task with an updated completed property
      // so we will save the mapped array to a new array with the correct/current`completed` property 
      const updatedTasksArray = tasks.map(task => {
         if (task.id === id) {
            return { ...task, text: newText, duedate: formattedDateTime };
         } else {
            return task;
         }
      });
      
      // console.log('tasks array value (BAD completed):', tasks );
      // console.log('updated tasks array after array map (GOOD completed?):', updatedTasksArray );

      setTasks(updatedTasksArray);

      // update localStorage after marking item completed
      const completedTasksList = JSON.stringify(updatedTasksArray);
      localStorage.setItem('tasks', completedTasksList);
      
      /*
      // another instance like toggleCompleted() where using the map() function inside of setTasks()
      // doesn't pass the current state of tasks to the setTasks() function
      setTasks(
         tasks.map(task => {
            if (task.id === id) {
               return { ...task, text: newText, duedate: formattedDateTime };
            } else {
               return task;
            }
         })
      );

      // update localStorage after updating item
      const updatedTasksList = JSON.stringify(tasks);
      localStorage.setItem('tasks', updatedTasksList);
      */
   }

   // Helper function - updates the `filter` state variable with the current value of the filter todo select menu
   function handleFilterChange(event) {
      console.log(event.target.value);
      setFilter(event.target.value);
   }

   // helper function - returns filtered tasks based on the current value of the filter todo select menu
   function getFilteredTasks() {
      //console.log(event);

      switch (filter) {
         case 'tasks-checked':
            return tasks.filter(task => task.completed);

         case 'tasks-unchecked':
            return tasks.filter(task => !task.completed);

         default:
            return tasks;
       }
   }

   /*
   const handleCloseOld = () => {
      setShowModal(false);
      setText('');
      setDateTime('');
   };
   */

   // handle closing modal window
   function handleClose() {
      setShowModal(false);
      //setText('');
      //setDateTime('');
      setAddEditMode('Add'); // reset label to 'Add' for modal window
      setCurrentTaskId(null); // Reset current task ID
   }

   // show modal window
   function handleShow() {
      setShowModal(true);
   }


   // display the edit todo modal window passing the current task selected for editing
   function editItemModal(task_id) {
      // alert(task_id);
      setAddEditMode('Edit'); // set add/edit label to 'Edit' for modal window
      setCurrentTaskId(task_id); // Reset current task ID
      setShowModal(true);
   }

   function loadDefaultTasks(defaultTasks) {
      if (window.confirm(`Overwrite the current tasks saved in Local Storage and load app default tasks?`))
      {
         setTasks(defaultTasks);

         // store updated tasks in local storage converting the tasks array of objects to a JSON string
         const updatedTasksList = JSON.stringify(defaultTasks);
         localStorage.setItem('tasks', updatedTasksList);
      }
   }

   return (
      <TodoListContext.Provider value={ tasks }>
      <DndContext
         collisionDetection={closestCenter}
         onDragEnd={handleDragEnd}
         modifiers={[restrictToVerticalAxis]}
         >
      <div className="container">
         <div className="header">
            <button className="top-add-todo-button" onClick={handleShow}>Add Todo</button>
            <TodoListHero completedTasks={completedTasks} totalTasks={totalTasks} />
            <div className="filter-container">
               <select className="filter-select" onChange={handleFilterChange}>
                  <option value="tasks-all">All</option>
                  <option value="tasks-checked">Checked</option>
                  <option value="tasks-unchecked">Unchecked</option>
               </select>
            </div>
         </div>
         
         
         <div className="todo-list">
         <SortableContext
            items={tasks}
            strategy={verticalListSortingStrategy}
            >
            {getFilteredTasks().map(task => (
                  <TodoListItem
                     key={task.id}
                     task={task}
                     deleteTask={deleteTask}
                     toggleCompleted={toggleCompletedAnonFunc}
                     updateTask={updateTask}
                     editItemModal={editItemModal}
                  />
            ))}
            {/* original output of tasks array with no filtering
            {tasks.map(task => (
               <TodoListItem
                  key={task.id}
                  task={task}
                  deleteTask={deleteTask}
                  toggleCompleted={toggleCompleted}
                  updateTask={updateTask}
               />
            ))} */}
            <div className="footerButtonContainer">
               <div className="footerButtonContainerLeft">
                  <button className="add-todo-button-footer" onClick={() => setShowModal(true)}>Add Todo</button>
               </div>
               <div className="footerButtonContainerRight">
                  <button className="load-default-todos-button" onClick={() => loadDefaultTasks(defaultTasks)}>Load Default Tasks (Reset LocalStorage)</button>
               </div>
            </div>
            </SortableContext>
         </div>

         {/* 
         The <TodoAddItemModal> component is being used in the TodoList component. Here's an explanation of the props being passed to <TodoAddItemModal>:

         1. showModal: This prop is passing the showModal state variable to the [TodoAddItemModal] (/src/components/TodoAddItemModal.js component. It allows the modal window to know whether it should be displayed or not based on the value of showModal.

         2. handleClose: This prop is passing the handleClose function to the [TodoAddItemModal] (/src/components/TodoAddItemModal.js) component. It enables the modal window to call the handleClose function when needed, typically to close the modal window.

         3. addTask: This prop is passing the [addTask] (\src\components\TodoList.js) function to the [TodoAddItemModal] (/src/components/TodoAddItemModal.js) component. It allows the modal window to call the [addTask] (\src\components\TodoList.js) function when a new task needs to be added based on user input within the modal.
         */}
         <TodoAddItemModal
            showModal={showModal}
            handleClose={handleClose}
            addTask={addTask}
            updateTask={updateTask}
            addEditMode={addEditMode}
            currentTaskId={currentTaskId}
         />
      </div>
      </DndContext>
      </TodoListContext.Provider>
   );
}

export default TodoList;
export { TodoListContext };

// src/components/TodoList.vue
<template>
   <div class="container">
      <div class="header">
         <button class="top-add-todo-button" @click="handleShow('Add', null)">Add Todo</button>

         <TodoListHero :completedTasks="completedTasks" :totalTasks="totalTasks" />

         <div class="filter-container">
            <select class="filter-select" @change="handleFilterChange($event)">
               <option value="tasks-all">All</option>
               <option value="tasks-checked">Checked</option>
               <option value="tasks-unchecked">Unchecked</option>
            </select>
         </div>
      </div>
      
      <div class="todo-list">
         <draggable v-model="tasks" item-key="id" @end="onEnd">
            <!--
            TodoListItem comments:
            
            Function: v-if checks if the element (current task) exists in the filteredTasks array. 
            The .some method returns true if at least one task in filteredTasks has an id matching element.id. 
            If true, the TodoListItem is rendered; otherwise, it is not.

            `task.id === element.id`: A comparison that checks if the id of the task 
            in filteredTasks matches the id of the current element.
            -->
            <template #item="{ element }">
               <TodoListItem
                  v-if="filteredTasks.some(task => task.id === element.id)"
                  :key="element.id"
                  :task="element"
                  @delete-task="deleteTask"
                  @toggle-completed="toggleCompleted"
                  @edit-task="editTask"
                  @add-task="addTask"
                  @edit-item-modal="editItemModal" />
            </template>
         </draggable>
         
         <!-- Original TodoListItem component without draggable -->
         <!-- 
         <TodoListItem
            v-for="task in filteredTasks"
            :key="task.id"
            :task="task"
            @delete-task="deleteTask"
            @toggle-completed="toggleCompleted"
            @edit-task="editTask"
            @add-task="addTask"
            @edit-item-modal="editItemModal" />
         -->

         <!-- <TodoListItem v-for="task in tasks" :key="task.id" :task="task" /> -->
          
         <!--
         :task="task"
            This binds the current task object in the iteration to the task prop of <TodoListItem>. 
            Each instance of <TodoListItem> will receive a task prop with the corresponding task 
            object from the tasks array to handle clicking the edit button.
         -->
         <!--
         * Original React component code
         <TodoListItem
            key={task.id}
            task={task}
            deleteTask={deleteTask}
            toggleCompleted={toggleCompletedAnonFunc}
            updateTask={updateTask}
            editItemModal={editItemModal} />
         -->
         
         <div class="footerButtonContainer">
            <div class="footerButtonContainerLeft">
               <button class="add-todo-button-footer" @click="handleShow('Add', null)">Add Todo</button>
            </div>
            <div class="footerButtonContainerRight">
               <button class="load-default-todos-button" value="Load" @click="loadDefaultTasks($event)">
                  Load Default Tasks (Reset LocalStorage)
               </button>
            </div>
         </div>
      </div>
      
      <TodoListModal
         v-show="showModal"
         :addEditMode="addEditMode"
         :task="currentTask"
         :tasks="tasks"
         :showModal="showModal"
         @add-task="addTask"
         @edit-task="editTask"
         @toggle-modal="toggleModalVisibility"
      />
      <!--
      <TodoAddItemModal
            showModal={showModal}
            addEditMode={addEditMode}
            addTask={addTask}
            updateTask={updateTask}
            currentTaskId={currentTaskId}
            toggleModalVisibility={toggleModalVisibility}
      />
      -->
   </div>
</template>

<script>
import draggable from 'vuedraggable';

import TodoListItem from './TodoListItem.vue';
import TodoListHero from './TodoListHero.vue';
import TodoListModal from './TodoListModal.vue';

export default {
   name: 'TodoList',

   // register our components
   components: {
      draggable, // for vuedraggable
      TodoListItem, 
      TodoListHero,
      TodoListModal
   },

   // props are ready only
   props: {
   },
   
   data() {
      return {
         drag: false, // for vuedraggable
         tasks: [],
         showModal: false,
         currentTask: null,
         filterType: 'tasks-all', // default filter type
         addEditMode: 'Add',
      }
   },

   /*
   Computed properties are:
      - like data properties, except they depend on other properties.

      - written like methods, but they do not accept any input arguments.

      - updated automatically when a dependency changes, while methods are 
        called on when something happens like with event handling for example

      - used when outputting something that depends on something else
   */
   computed: {
      // computed property to filter tasks
      filteredTasks() {
         console.log('filteredTasks, filterType: ' + this.filterType);

         switch (this.filterType) {
            case 'tasks-checked':
               return this.tasks.filter(task => task.completed);

            case 'tasks-unchecked':
               return this.tasks.filter(task => !task.completed);

            default:
               return this.tasks;
         }
      },
      
      // computed property to return the number of completed tasks
      completedTasks() {
         return this.tasks.filter(task => task.completed).length
      },
      
      // computed property to return the total number of tasks
      totalTasks() {
         return this.tasks.length;
      },
   },
   
   // mounted lifecycle hook happens after the Vue component is mounted to the DOM
   mounted() {
      const storedTasks = localStorage.getItem('tasks');

      // load tasks from localStorage if it exists
      if (storedTasks) {
         this.tasks = JSON.parse(storedTasks);
      }
      // load default tasks
      else {
         this.tasks = this.loadDefaultTasks();
      }
   },

   // Methods are functions that belong to the vue instance under the 'methods' property
   // Tip: We need to write `this.` as prefix to refer to a data property from inside a method.
   methods: {
      // drag and drop end event handler
      onEnd(event) {
         // convert tasks array to JSON string
         const updatedTasksList = JSON.stringify(this.tasks);

         // save reordered tasks to localStorage
         localStorage.setItem('tasks', updatedTasksList);
         console.log('Drag ended:', event);
      },

      // toggle the completion status of a todo item
      toggleCompleted(id) {
         //alert('toggleCompleted in TodoList.vue, id: ' + id);

         this.tasks = this.tasks.map(task => {
            if (task.id === id) {
               return { ...task, completed: !task.completed };
            } else {
               return task;
            }
         });

         const updatedTasksList = JSON.stringify(this.tasks);
         localStorage.setItem('tasks', updatedTasksList);
      },

      // display the add/edit todo modal window
      handleShow(mode, task) {
         // console.log('handleShow in TodoList.vue, mode: ' + mode + ', task: ', task);
         
         this.addEditMode = mode; // adjust 'Add' or 'Edit' label in modal
         this.currentTask = task; // pass task object to modal
         this.showModal = true;   //
      },

      // toggle modal window visibility
      toggleModalVisibility() {
         // alert('toggleModalVisibility from TodoList.vue');
         this.showModal = !this.showModal;

         // clear currentTask if modal is closed
         if (!this.showModal) {
            // alert('clearing currentTask in TodoList.vue');
            
            // Reset currentTask to null if modal is closed to prevent blank form input values
            // on multiple edits on the same task
            this.currentTask = null;
         }
      },

      // filter tasks based on the filter type
      handleFilterChange(e) {
         console.log('handleFilterChange, event value: ' + e.target.value);

         this.filterType = e.target.value;
      },

      // add a new task to the tasks array
      addTask(newTask) {
         //alert('addTask, event value: ' + e.target.value);
         this.tasks.push(newTask);

         const updatedTasksList = JSON.stringify(this.tasks);
         localStorage.setItem('tasks', updatedTasksList);
      },

      // display the edit task modal for the selected task
      editItemModal(currentTaskId, addEditMode) {
         //alert('editItemModal in TodoList.vue. Task id: ' + currentTaskId);
         
         const task = this.tasks.find(task => task.id === currentTaskId);

         if (task) {
            this.handleShow('Edit', task);
         } else {
            console.error(`Task with id ${currentTaskId} not found`);
         }
      },

      // update a task in the tasks array
      editTask(currentTaskId, updatedTask) {
         // console.log(updatedTask);

         // find the index of the task to be updated
         const index = this.tasks.findIndex(task => task.id === currentTaskId);

         // if the task is found, update it with the updatedTask object
         if (index !== -1) {
            this.tasks.splice(index, 1, updatedTask);
         }

         // update localStorage after editing item
         const updatedTasksList = JSON.stringify(this.tasks);
         localStorage.setItem('tasks', updatedTasksList);
      },

      // delete a task from the tasks array
      deleteTask(currentTaskId) {
         // alert('deleteTask in TodoList.vue. Task id: ');
         this.tasks = this.tasks.filter(task => task.id !== currentTaskId);

         // update localStorage after deleting item (convert tasks array to JSON string)
         const updatedTasksList = JSON.stringify(this.tasks.filter(task => task.id !== currentTaskId));
         localStorage.setItem('tasks', updatedTasksList);
      },

      // load default tasks
      loadDefaultTasks(e) {
         // alert('loadDefaultTasks, event value: ' + e.target.value);

         const defaultTasks = [
            {
               id: 1,
               text: "Edit item  - watch out for long text lines that wrap",
               duedate: "2099-01-01 12:00",
               completed: true,
               position: 1
            },
            {
               id: 2,
               text: "Add todo item",
               duedate: "",
               completed: true,
               position: 2
            },
            {
               id: 3,
               text: "Delete todo item",
               duedate: "",
               completed: true,
               position: 3
            },
            {
               id: 4,
               text: "localStorage save/read of todo items",
               duedate: "",
               completed: true,
               position: 4
            },
            {
               id: 5,
               text: "Drag and drop reordering of todo items",
               duedate: "2024-08-01 12:00",
               completed: false,
               position: 5
            }
         ];

         // store updated tasks in local storage converting the tasks array of objects to a JSON string
         const updatedTasksList = JSON.stringify(defaultTasks);
         localStorage.setItem('tasks', updatedTasksList);
         
         // update tasks array with default tasks array
         this.tasks = defaultTasks;
      }
   }
};
</script>

<style>
/* App.css */
body {
   font-family: 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
   background-color: #cce8f3;
}

textarea, input {
   font-family: 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
}

input[type="checkbox"] {
   transform: scale(1.5);
   cursor: pointer;
}


.container {
   width: 450px;
   /* border: 3px solid #000; */
   margin: auto; /* center the container horizontally */
}

.header {
   width: 100%;
   display: flex;
   justify-content: space-between;
   align-items: center;
   padding-bottom: 10px;
   margin: 0 auto;
   /* border: 3px solid #be02f2; */
}

.todo-list {
   margin: 0 auto;
   padding-bottom: 30px;
}


.todo-item {
   display: flex;
   align-items: center;
   padding: 12px;
   background-color: #f8f9fa;
   color: #333;
   border-radius: 4px;
   margin-bottom: 8px;
   box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
 }


.top-add-todo-button {
   background-color: #007bff;
   color: white;
   border: none;
   padding: 8px 10px;
   border-radius: 4px;
   cursor: pointer;
   transition: background-color 0.3s ease;
}

.filter-select {
   padding: 7px 0 7px 10px;
   border-radius: 4px;
   border: 1px solid #ccc;
   margin-left: auto;
}


h1 {
   max-width: 400px;
   margin: 0 auto;
   text-align: center;
   color: #555;
   margin-top: 15px;
   margin-bottom: 15px;
}

.edit-input {
   text-align: left;
   width: 90%;
   border-radius: 3px;
}

.todo-text {
   /* cursor: pointer; */
}
 

 /* Drag handle for dnd kit sortable */
.drag-handle {
   cursor: grab;
   padding-right: 5px;
   margin-right: 5px;
   touch-action: none;
}

/* Increase drag handle size on mobile devices */
@media (max-width: 600px) {
   .drag-handle {
     padding-right: 15px; /* Increase padding for easier touch interaction */
     margin-right: 10px; /* Increase margin if needed */
     font-size: 1.5rem; /* Increase font size if there's text inside the handle */
     touch-action: none;
   }
 }
 
.todo-content {
   display: flex;
   align-items: center;
   width: 100%;
}

.todo-content:has(:checked) .todo-text {
   color: #666;
   text-decoration: line-through;
}

.todo-content {
   display: flex;
   justify-content: space-between;
   width: 100%;
}

.todo-text-container {
   display: flex;
   flex-direction: column;
   padding: 0 5px 0 0;
}

.due-date {
   padding-top: 2px;
   font-size: 0.85rem;
   color: #888;
}

/* left algin todo items */
.todo-item div {
   flex: 1;
   margin: 0;
}
 
.todo-item div.completed {
   text-decoration: line-through;
   color: #888;
}

.todo-item .edit-button {
   background-color: #888;
   color: white;
   border: none;
   padding: 6px 12px;
   border-radius: 4px;
   margin-right: 5px;
   cursor: pointer;
   transition: background-color 0.1s ease;
}

.todo-item .edit-button:hover {
   background-color: #007cf9bf;
}
 
.todo-item .delete-button {
   background-color: #888;
   color: white;
   border: none;
   padding: 6px 12px;
   border-radius: 4px;
   cursor: pointer;
   transition: background-color 0.1s ease;
}
 
.todo-item .delete-button:hover {
   background-color: #af2432;
}

.todo-item input[type="checkbox"] {
   margin-right: 12px;
}

.new-todo-input {
   width: 100%;
   max-width: 400px;
   margin: 0 auto;
   padding: 8px;
   border: 1px solid #ccc;
   border-radius: 4px;
   margin-bottom: 20px;
}


.footerButtonContainer {
   /* border: 1px solid #000; */
   display: flex;
   justify-content: space-between;
    /* Ensure the container takes the full width */
}
 
.add-todo-button-footer, .load-default-todos-button {
   padding: 10px;
   margin: 0;
   box-sizing: border-box;
}
 
.footerButtonContainerLeft {
   display: flex;
   justify-content: flex-start;
}
 
.footerButtonContainerRight {
   display: flex;
   justify-content: flex-end;
}



.add-todo-button-footer {
   background-color: #007bff;
   color: white;
   border: none;
   padding: 8px 10px;
   margin: 2px 0 0 0;
   border-radius: 4px;
   cursor: pointer;
   transition: background-color 0.3s ease;
}

.load-default-todos-button {
   background-color: #730584;
   color: white;
   border: none;
   padding: 8px 10px;
   margin: 2px 0 0 10px;
   border-radius: 4px;
   cursor: pointer;
   transition: background-color 0.3s ease;
}
</style>
